name = "rudderstack-v3-reverse-proxy"  # Replace with your project name
compatibility_date = "2024-08-15"
main = "src/index.js"
account_id = "XXX"  # Replace with your Cloudflare account ID
kv_namespaces = [
  { binding = "KV", id = "XXX" }
]
[env.production]
name = "production"
workers_dev = false